package com.mellivora.pundit.entity;

import java.util.Date;

public class MiShop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.shop_id
     *
     * @mbg.generated
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.shop_name
     *
     * @mbg.generated
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.header
     *
     * @mbg.generated
     */
    private String header;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.address_province
     *
     * @mbg.generated
     */
    private String addressProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.address_city
     *
     * @mbg.generated
     */
    private String addressCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.address_area
     *
     * @mbg.generated
     */
    private String addressArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.license
     *
     * @mbg.generated
     */
    private String license;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.license_no
     *
     * @mbg.generated
     */
    private String licenseNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.shop_image
     *
     * @mbg.generated
     */
    private String shopImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.describe
     *
     * @mbg.generated
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.open_all_day
     *
     * @mbg.generated
     */
    private String openAllDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.business_start_time
     *
     * @mbg.generated
     */
    private String businessStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.business_end_time
     *
     * @mbg.generated
     */
    private String businessEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.fee
     *
     * @mbg.generated
     */
    private Double fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.create_id
     *
     * @mbg.generated
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.update_id
     *
     * @mbg.generated
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.del_flag
     *
     * @mbg.generated
     */
    private Boolean delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.remarke
     *
     * @mbg.generated
     */
    private String remarke;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mi_shop.details_note
     *
     * @mbg.generated
     */
    private String detailsNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.id
     *
     * @return the value of mi_shop.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.id
     *
     * @param id the value for mi_shop.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.shop_id
     *
     * @return the value of mi_shop.shop_id
     *
     * @mbg.generated
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.shop_id
     *
     * @param shopId the value for mi_shop.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.phone
     *
     * @return the value of mi_shop.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.phone
     *
     * @param phone the value for mi_shop.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.shop_name
     *
     * @return the value of mi_shop.shop_name
     *
     * @mbg.generated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.shop_name
     *
     * @param shopName the value for mi_shop.shop_name
     *
     * @mbg.generated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.header
     *
     * @return the value of mi_shop.header
     *
     * @mbg.generated
     */
    public String getHeader() {
        return header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.header
     *
     * @param header the value for mi_shop.header
     *
     * @mbg.generated
     */
    public void setHeader(String header) {
        this.header = header == null ? null : header.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.address_province
     *
     * @return the value of mi_shop.address_province
     *
     * @mbg.generated
     */
    public String getAddressProvince() {
        return addressProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.address_province
     *
     * @param addressProvince the value for mi_shop.address_province
     *
     * @mbg.generated
     */
    public void setAddressProvince(String addressProvince) {
        this.addressProvince = addressProvince == null ? null : addressProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.address_city
     *
     * @return the value of mi_shop.address_city
     *
     * @mbg.generated
     */
    public String getAddressCity() {
        return addressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.address_city
     *
     * @param addressCity the value for mi_shop.address_city
     *
     * @mbg.generated
     */
    public void setAddressCity(String addressCity) {
        this.addressCity = addressCity == null ? null : addressCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.address_area
     *
     * @return the value of mi_shop.address_area
     *
     * @mbg.generated
     */
    public String getAddressArea() {
        return addressArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.address_area
     *
     * @param addressArea the value for mi_shop.address_area
     *
     * @mbg.generated
     */
    public void setAddressArea(String addressArea) {
        this.addressArea = addressArea == null ? null : addressArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.address
     *
     * @return the value of mi_shop.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.address
     *
     * @param address the value for mi_shop.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.license
     *
     * @return the value of mi_shop.license
     *
     * @mbg.generated
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.license
     *
     * @param license the value for mi_shop.license
     *
     * @mbg.generated
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.license_no
     *
     * @return the value of mi_shop.license_no
     *
     * @mbg.generated
     */
    public String getLicenseNo() {
        return licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.license_no
     *
     * @param licenseNo the value for mi_shop.license_no
     *
     * @mbg.generated
     */
    public void setLicenseNo(String licenseNo) {
        this.licenseNo = licenseNo == null ? null : licenseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.shop_image
     *
     * @return the value of mi_shop.shop_image
     *
     * @mbg.generated
     */
    public String getShopImage() {
        return shopImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.shop_image
     *
     * @param shopImage the value for mi_shop.shop_image
     *
     * @mbg.generated
     */
    public void setShopImage(String shopImage) {
        this.shopImage = shopImage == null ? null : shopImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.describe
     *
     * @return the value of mi_shop.describe
     *
     * @mbg.generated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.describe
     *
     * @param describe the value for mi_shop.describe
     *
     * @mbg.generated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.open_all_day
     *
     * @return the value of mi_shop.open_all_day
     *
     * @mbg.generated
     */
    public String getOpenAllDay() {
        return openAllDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.open_all_day
     *
     * @param openAllDay the value for mi_shop.open_all_day
     *
     * @mbg.generated
     */
    public void setOpenAllDay(String openAllDay) {
        this.openAllDay = openAllDay == null ? null : openAllDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.business_start_time
     *
     * @return the value of mi_shop.business_start_time
     *
     * @mbg.generated
     */
    public String getBusinessStartTime() {
        return businessStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.business_start_time
     *
     * @param businessStartTime the value for mi_shop.business_start_time
     *
     * @mbg.generated
     */
    public void setBusinessStartTime(String businessStartTime) {
        this.businessStartTime = businessStartTime == null ? null : businessStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.business_end_time
     *
     * @return the value of mi_shop.business_end_time
     *
     * @mbg.generated
     */
    public String getBusinessEndTime() {
        return businessEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.business_end_time
     *
     * @param businessEndTime the value for mi_shop.business_end_time
     *
     * @mbg.generated
     */
    public void setBusinessEndTime(String businessEndTime) {
        this.businessEndTime = businessEndTime == null ? null : businessEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.fee
     *
     * @return the value of mi_shop.fee
     *
     * @mbg.generated
     */
    public Double getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.fee
     *
     * @param fee the value for mi_shop.fee
     *
     * @mbg.generated
     */
    public void setFee(Double fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.status
     *
     * @return the value of mi_shop.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.status
     *
     * @param status the value for mi_shop.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.create_time
     *
     * @return the value of mi_shop.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.create_time
     *
     * @param createTime the value for mi_shop.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.create_id
     *
     * @return the value of mi_shop.create_id
     *
     * @mbg.generated
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.create_id
     *
     * @param createId the value for mi_shop.create_id
     *
     * @mbg.generated
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.update_time
     *
     * @return the value of mi_shop.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.update_time
     *
     * @param updateTime the value for mi_shop.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.update_id
     *
     * @return the value of mi_shop.update_id
     *
     * @mbg.generated
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.update_id
     *
     * @param updateId the value for mi_shop.update_id
     *
     * @mbg.generated
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.del_flag
     *
     * @return the value of mi_shop.del_flag
     *
     * @mbg.generated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.del_flag
     *
     * @param delFlag the value for mi_shop.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.remarke
     *
     * @return the value of mi_shop.remarke
     *
     * @mbg.generated
     */
    public String getRemarke() {
        return remarke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.remarke
     *
     * @param remarke the value for mi_shop.remarke
     *
     * @mbg.generated
     */
    public void setRemarke(String remarke) {
        this.remarke = remarke == null ? null : remarke.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mi_shop.details_note
     *
     * @return the value of mi_shop.details_note
     *
     * @mbg.generated
     */
    public String getDetailsNote() {
        return detailsNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mi_shop.details_note
     *
     * @param detailsNote the value for mi_shop.details_note
     *
     * @mbg.generated
     */
    public void setDetailsNote(String detailsNote) {
        this.detailsNote = detailsNote == null ? null : detailsNote.trim();
    }
}